spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fullerting
    username: ssafy
    password: ssafy

  data:
    redis:
      host: j10C102.p.ssafy.io
      port: 6379 

  security:
    user:
      name: test
      password: 1234

  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialone
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverything
    accesstime: 3600000  # 1H
    refreshtime: 604800000 # 7Days

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    credentials:
      access-key: AKIAW3MEAWFWGVMIB3VX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: fullerting-s3-v2
      stack:
        auto: false



logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG

      hibernate:
        type:
          descriptor:
            sql: trace
