spring:
  datasource:
    url: jdbc:mysql://j10C102.p.ssafy.io:3306/fullerting
    username: fulldba
    password: full202403110344

  data:
    redis:
      host: j10C102.p.ssafy.io
      port: 6379

  security:
    user:
      name: test
      password: 1234

  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialone
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverything
    accesstime: 3600000  # 1H
    refreshtime: 604800000 # 7Days

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: false  # jpa 쿼리문 출력 설정
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    credentials:
      access-key: AKIAW3MEAWFWGVMIB3VX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: fullerting-s3-v2
      stack:
        auto: false

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html


logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG


fcm:
  service-account-file: key/fullerting-fcm-firebase-adminsdk-rjmjj-0e19a90e90.json
  topic-name: alarm
  project-id: fullerting-fcm

#      hibernate:
#        type:
#          descriptor:
#            sql: trace
