spring:
  datasource:
    url: jdbc:mysql://j10C102.p.ssafy.io:3306/fullerting
    username: fulldba
    password: full202403110344

  data:
    redis:
      host: j10C102.p.ssafy.io
      port: 6379

  security:
    user:
      name: test
      password: 1234

  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialoneeverydayeverytimedontbeforgetthis
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverythingrememberyourinnervoice
    accesstime: 86400000 # 24H
    refreshtime: 604800000 # 7Days


logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG